namespace CRAVENEST.Model
{
    public class Order
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public decimal TotalAmount { get; set; }
        public string Status { get; set; } = "Pending";
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }
        public int SignUpId { get; set; }
        public List<OrderItem> Items { get; set; } = new List<OrderItem>();
    }

    public class OrderItem
    {
        // Fields sent from the frontend
        public int FoodItemId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }

        // Fields generated by the backend or not required at creation
        public int? OrderItemId { get; set; }  // Nullable
        public int? OrderId { get; set; }  // Nullable
        public string? FoodItemName { get; set; }  // Nullable, can be set later
    }

}
